apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gosample
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gosample
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
