version: "3"
services:
  kong-database:
    image: postgres:9.6
    restart: always
    volumes:
      - kong-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=kong_db
    ports:
      - 5432:5432
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "kong_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migrate:
    image: kong:2.3.3
    restart: on-failure
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=user
      - KONG_PG_PASSWORD=12345
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - kong-net
  
  kong:
    image: kong:2.3.3
    restart: always
    environment:
      - KONG_LOG_LEVEL=debug
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=user
      - KONG_PG_PASSWORD=12345
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migrate:
        condition: service_started
    networks:
      - kong-net

  konga-prepare:
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://user:12345@kong-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
     kong-database:
        condition: service_healthy

  konga:
    image: pantsel/konga:0.14.9
    restart: on-failure
    networks:
      - kong-net
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=user
      - DB_PASSWORD=12345
      - TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      - DB_DATABASE=konga_db
      - NODE_ENV=production
    depends_on:
      kong-database:
        condition: service_healthy
      konga-prepare:
        condition: service_started
    ports:
      - "1337:1337"

volumes:
  kong-db:

networks:
  kong-net:
    driver: bridge
